Re-save cache every run. Add `/compiled` and `/logs`. Auto-remove old matching caches.
julia-actions/cache pull request #71
Opened 2023-11-19 05:20 UTC by IanButterworth

Alternative to https://github.com/julia-actions/cache/pull/45

This keeps the depot in one cache file for the given key, which  is sensitive to julia version, OS and arch (for the usual matrix var names, and there's a note if not).
It also re-saves the cache every run, removing the previous cache that was used.
By including `/logs` it also enables automatic `Pkg.gc()` to keep the depot size down, given that the depot will be restored>used>saved>restored>used>saved.. sequentially through the runs.

Regarding the split strategy in #45 , while there are some elements of the depot that are cross-OS compatible (`/packages`, `/registries`), for precompilation to remain hot, and for automatic `Pkg.gc()` to work properly, I think the depot should be cached in lock-step as a whole.

To implement this, because neither Github or `actions/cache` expose a way to update a cache file at a key, we have to run our own deletion just before the `actions/cache` save post step. So for a given key, there will only ever be one cache retained. This reduces the chance of the automatic eviction github does evicting a useful cache over an less useful one.

## Demo

You can see it in action here https://github.com/JuliaIO/PNGFiles.jl/pull/72
Tests have been disabled, so it's just installation and loading.

First commit was with no cache files in the repo.
Second empty commit benefitted from the caching.

On linux 1.11 goes from 2 minutes to 40s

Cache sizes are all around 30 MB.

And there will only ever be the same number as the permutations of the matrix, so 15 in that repo, which is a common number.

I will note that it seems there's been a sizeable regression in precompile duration in master recently. Needs investigating.

## How to release

It'd be nice to get this widely adopted, so I'm intrigued about releasing this as a minor change.
There's no breakage to the API, except for changes to defaults.

2023-11-19 19:18 UTC, rikhuijzer approved these changes
Nice. Makes sense to me. The cache deletion logic looks a bit like a "hack", but it makes sense to me. For Javascript libraries, not updating the cache should be fine for small dependency changes. However, for Julia small dependency changes can outdate almost all compiled artifacts, so that's probably why forcing a new cache each time makes sense here?

One question regarding the cache delete logic. Isn't the most recent cache also deleted?

2023-11-19 19:18 UTC, rikhuijzer commented on handle_caches.jl
> +        append!(caches, hits)
```suggestion
        append!(caches, hits)
        search_again = length(hits) == 100
```

2023-11-19 19:18 UTC, rikhuijzer commented on handle_caches.jl
> +        search_again = length(hits) == 100
```suggestion
```
Variable can be moved down

2023-11-19 19:18 UTC, rikhuijzer commented on handle_caches.jl
> +end
```suggestion
else
    throw(ArgumentError("Unexpected first argument: $func"))
end
```

2023-11-19 19:19 UTC, IanButterworth commented on handle_caches.jl
> +        append!(caches, hits)
This isn't correct. The logic is that if the unfilitered original list is equal to 100, then there are more. After the filter we don't know

2023-11-19 19:21 UTC, IanButterworth commented
> isn't the most recent cache deleted?

No, the cache deletion step happens just before the cache/save step.

The way post jobs are queued is a little confusing.

2023-11-19 19:23 UTC, rikhuijzer commented on handle_caches.jl
> +        for c in hits
```suggestion
        # We can delete everything that matches the restore key because the new cache is saved later.
        for c in hits
```

2023-11-19 20:08 UTC, IanButterworth commented
Ideally we'd only save if there were changes in the depot, but in practice that will be true every run because of the usage logs being updated. And usage logs allow us to do auto Pkg.gc

It kind of puts the decision on how to manage the depot in Julia's hands, which I think makes sense.

2023-11-19 22:32 UTC, IanButterworth commented
Reminder to myself. We might want to add an input to turn off cache deletion.

2023-11-19 23:28 UTC, IanButterworth commented on README.md
> +Which means your caches files will not grow needlessly. Github also deletes cache files after 7 days.
```suggestion
Which means your caches files will not grow needlessly. Github also deletes cache files after [90 days and up to 400 days for private repos](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization)
```

2023-11-20 18:36 UTC, IanButterworth commented
If you're able to review @SaschaMann let me know, otherwise I'll merge and release this as v1.4.0 tomorrow. (or let me know if you want more time)

2023-11-21 20:20 UTC, IanButterworth commented on action.yml
> +          ${{ inputs.cache-name }}-${{ matrix.julia-version }}-${{ runner.os }}-${{ matrix.arch }}
Actually `version` might be more common than `julia-version`.

Or we just be sensitive to both like this (given non-existant matrix var is interpolated as an empty string)
```suggestion
          ${{ inputs.cache-name }}-${{ matrix.version }}${{ matrix.julia-version }}-${{ runner.os }}-${{ matrix.arch }}
```

2023-11-22 02:13 UTC, IanButterworth commented
I've done some tidying. @rikhuijzer would you mind taking one last look before I merge? This is in the context of it being a non-breaking release

2023-11-22 08:13 UTC, rikhuijzer approved these changes
I have to admit that I don't fully understand everything because I find caching logic complex. Having said that, I'm in favor of going ahead and merging 👍

2023-11-22 08:13 UTC, rikhuijzer commented on README.md
> +The benefit of this is that downloading one big file is quicker than downloading many different files from many different locations
```suggestion
The benefit of caching is that downloading one big file is quicker than downloading many different files from many different locations
```
Otherwise it looks like "this" refers to the resaving under new key and previous cache deletion logic.

2023-11-22 10:28 UTC, SaschaMann requested changes
Looks good for the most part, though I didn't have the time to review it thoroughly.

2023-11-22 10:28 UTC, SaschaMann commented on action.yml
> +    - uses: pyTooling/Actions/with-post-step@v0.4.6
This action appears to be quite simple. Given we expect the cache action to be used across such a wide range of repos and perhaps also in contexts with higher permissions than `read`, we should consider replicating its logic in here.

At the very least, it should be pinned at a commit hash like the other actions. [This is what the request-changes status is for.]

Depending on third party actions adds a lot of attack surface to this action and thus to the ecosystem, so it should be carefully considered.

2023-11-22 18:25 UTC, IanButterworth commented on action.yml
> +    - uses: pyTooling/Actions/with-post-step@v0.4.6
Yeah. For now I've changed it to the commit hash, but I may bring it over as others have done the same for this action, with a note for the license

2023-11-22 18:37 UTC, IanButterworth commented
Ok. I've found a better way than guessing matrix var names.. now this collates all matrix vars in the order they are entered automatically into a string.

So 
```
      matrix:
        julia-version: ['1', '^1.10.0-rc1', 'nightly']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch: [x64, x86]
```
becomes, for instance `1-ubuntu-latest-x64`
And I included `runner.OS` just in case it's not part of the matrix.

So a full default key looks like `julia-cache-1-ubuntu-latest-x64-Linux-6961372938-1`


You can see the latest in action here
https://github.com/JuliaIO/PNGFiles.jl/actions/runs/6961372938/attempts/1?pr=72
and the re-run with a hot cache (although some of the nightlies updated)
https://github.com/JuliaIO/PNGFiles.jl/actions/runs/6961372938/attempts/2?pr=72

2023-11-22 18:55 UTC, rikhuijzer commented on action.yml
> +    - uses: pyTooling/Actions/with-post-step@v0.4.6
Maybe something like this could work also (https://docs.github.com/en/actions/learn-github-actions/expressions#always)?

```
    - run: |
        echo "This is the post step"
        # Add your post step logic here
      shell: bash
      if: always() 
```

2023-11-22 19:02 UTC, IanButterworth commented on action.yml
> +    - uses: pyTooling/Actions/with-post-step@v0.4.6
I'm not sure how that would work for our needs. What we need to do is inject a step after the users last step, but before the cache/save step. IIUC the only way to do that is to use the `post` approach, and setting that up after the `cache` step here means we get that ordering.

2023-11-22 19:14 UTC, rikhuijzer commented
For future reference, here are the numbers from the two runs:

<details>

| Test Description | First Run | Second Run |
|------------------|----------------|----------------|
| test (nightly, macOS-latest) | 2m 56s | 3m 38s |
| test (nightly, ubuntu-latest) | 2m 1s | 38s |
| test (nightly, ubuntu-latest, ...) | 2m 0s | 1m 54s |
| test (nightly, windows-latest, ...) | 3m 5s | 1m 36s |
| test (nightly, windows-latest, ...) | 3m 4s | 1m 29s |
| test (^1.10.0-rc1, macOS-latest, ...) | 1m 59s | 2m 0s |
| test (^1.10.0-rc1, ubuntu-latest, ...) | 1m 38s | 1m 36s |
| test (^1.10.0-rc1, ubuntu-latest, ...) | 1m 35s | 1m 28s |
| test (^1.10.0-rc1, windows-latest, ...) | 2m 39s | 1m 19s |
| test (^1.10.0-rc1, windows-latest, ...) | 2m 35s | 1m 8s |
| test (1, macOS-latest, ...) | 3m 22s | 1m 20s |
| test (1, ubuntu-latest, ...) | 1m 35s | 37s |
| test (1, ubuntu-latest, ...) | 1m 32s | 40s |
| test (1, windows-latest, ...) | 2m 39s | 1m 2s |
| test (1, windows-latest, ...) | 2m 51s | 1m 21s |

(Credits to ChatGPT. I just threw in two screenshots asked for a table. I manually verified all the numbers. They are correct.)
</details>

Nice speedup  🚀

2023-11-22 19:20 UTC, IanButterworth commented
Note that some of the nightly versions changed between runs, so had to do re-precompilation.. That will be an issue until 1.11 is released.

But yeah, it's surprisingly effective on 1.9, but unfortunately that gain is lost in 1.10.0-rc1 because of more stdlibs outside of the sysimage.
I'm going to look into whether we can fix that regression by moving away from mtime sensitivity when it comes to stdlibs. I.e. reviving https://github.com/JuliaLang/julia/pull/50919

2023-11-22 19:21 UTC, IanButterworth commented on action.yml
> +    - uses: pyTooling/Actions/with-post-step@v0.4.6
Now vendored ourself (as people have been doing elsewhere https://github.com/actions/runner/issues/1478#issuecomment-1586249440)

2023-11-22 19:35 UTC, IanButterworth commented on action.yml
> +    - uses: pyTooling/Actions/with-post-step@v0.4.6
Ugh.. vendoring it ourself is complicated.. relative paths work wrt the working directory, so CI passes here but fails when actually run on other projects. And we can't do `${{ github.action_path }}/with-post-step` apparently.

Anyone know of a way around this? 
Note that we cannot simply bring the logic into our `.yml` because it requires it to be a node action. `post` steps aren't possible on `composite` actions.

2023-11-22 19:42 UTC, IanButterworth commented on action.yml
> +    - uses: pyTooling/Actions/with-post-step@v0.4.6
Ok this works, and update the commit once squashed onto main
```
    - uses: julia-actions/cache/with-post-step@5d5ff4e210fbccb3e875c042dd7c8e6f9c31e1f0
```

2023-11-22 19:58 UTC, IanButterworth commented
Ok. Should be good to go now. Final run check (ignore that these are opposite order.. I deleted the caches after attempt #2)

| : cold cache : | : hot cache : |
| ---- | ---- | 
| https://github.com/JuliaIO/PNGFiles.jl/actions/runs/6961978935/attempts/3?pr=72 | https://github.com/JuliaIO/PNGFiles.jl/actions/runs/6961978935/attempts/2?pr=72 |
|  <img width="183" alt="Screenshot 2023-11-22 at 2 56 43 PM" src="https://github.com/julia-actions/cache/assets/1694067/7e7b5ba7-d370-4191-bf57-a96a2536c300"> | <img width="197" alt="Screenshot 2023-11-22 at 2 53 02 PM" src="https://github.com/julia-actions/cache/assets/1694067/b460e0e1-16f6-4aa5-8c19-6ca3aec649c7"> |


Note: I noticed that the two nightly macOS runs are on the same julia commit.. so I think there might be an issue preventing macOS from avoiding re-precompilation. That can be investigated independently.

2023-11-22 21:10 UTC, IanButterworth commented
I think we may want to also include the job name in the key automatically?

2023-11-22 21:11 UTC, IanButterworth commented
Also from testing this with a self hosted runner. We can't assume `jq` is installed

2023-11-22 21:19 UTC, IanButterworth commented
Also, if there's no matrix
```
jq: error (at <stdin>:1): string ("") has no keys
```

2023-11-22 21:28 UTC, SaschaMann commented on action.yml
> +    - uses: pyTooling/Actions/with-post-step@v0.4.6
I'm not sure vendoring comes with any benefits over using a commit hash unless that repo is deleted or something similar. I was thinking that it looked simple enough that we might be able to inline it (that usually also makes it clearer what's going on in case something goes wrong) but if that's not the case, I think pinning it to a  hash in their repo is sufficient.

2023-11-22 21:29 UTC, IanButterworth commented on action.yml
> +    - uses: pyTooling/Actions/with-post-step@v0.4.6
ok

2023-11-22 21:31 UTC, SaschaMann commented
> Also from testing this with a self hosted runner. We can't assume `jq` is installed

I'm not too worried about that. Requiring `jq` as a dependency seems fine, it's an extremely common tool and it's available on all hosted runners anyway.

2023-11-22 22:06 UTC, IanButterworth commented
Note to self. Hitting this on a private repo during the post step, which doesn't currently make sense to me..
```
Setting working directory to /home/runner/work/Foo.jl/Foo.jl
failed to run git: fatal: not a git repository (or any of the parent directories): .git

ERROR: LoadError: failed process: Process(`gh cache list --limit 100`, ProcessExited(1)) [1]
```

2023-11-23 02:09 UTC, IanButterworth commented
I'm noticing some things testing this with a larger less standard package setup, so I'm investigating.

2023-11-23 10:58 UTC, SaschaMann approved these changes
My concern above has been fixed, so from my side once you consider this good to go, I'm happy to have it merged.

2023-11-25 02:35 UTC, IanButterworth commented
Ok, some tweaks:
- Added `include-matrix` input bool to allow the user to disable automatically including the matrix. While including the matrix is a good default for standard julia package CI, a use case I have for it is where a single runner runner runs, then a matrix of many different permutations, and I want the matrix to use the cache from the first runner. So in that case ignoring the matrix is beneficial
- Pass the run repo explicitly to the `gh cache` calls as it cannot be assumed that the working directory is the repo of the run
- Using an underscore after the restore key helps to indicate the end of the part that restore keys should match. Otherwise too many caches were deleted
- Explicitly run `Pkg.gc` before save to help keep the cache size down
- List the depot tree size after restore, for info

2023-11-25 05:07 UTC, IanButterworth commented
ugh.. turns out you can just `${{ join(matrix.*, '-') }}` to get all matrix values joined with `-`.

So that avoids the need for `jq` 🎉 

I'll go ahead and merge, and release tomorrow as 1.4.0 unless I hear otherwise.

2023-11-25 05:08 UTC, merged